// Generated by gencpp from file rss2_msgsrv_pkg/srv_turtlebot_moveResponse.msg
// DO NOT EDIT!


#ifndef RSS2_MSGSRV_PKG_MESSAGE_SRV_TURTLEBOT_MOVERESPONSE_H
#define RSS2_MSGSRV_PKG_MESSAGE_SRV_TURTLEBOT_MOVERESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rss2_msgsrv_pkg
{
template <class ContainerAllocator>
struct srv_turtlebot_moveResponse_
{
  typedef srv_turtlebot_moveResponse_<ContainerAllocator> Type;

  srv_turtlebot_moveResponse_()
    : success(false)  {
    }
  srv_turtlebot_moveResponse_(const ContainerAllocator& _alloc)
    : success(false)  {
  (void)_alloc;
    }



   typedef uint8_t _success_type;
  _success_type success;





  typedef boost::shared_ptr< ::rss2_msgsrv_pkg::srv_turtlebot_moveResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rss2_msgsrv_pkg::srv_turtlebot_moveResponse_<ContainerAllocator> const> ConstPtr;

}; // struct srv_turtlebot_moveResponse_

typedef ::rss2_msgsrv_pkg::srv_turtlebot_moveResponse_<std::allocator<void> > srv_turtlebot_moveResponse;

typedef boost::shared_ptr< ::rss2_msgsrv_pkg::srv_turtlebot_moveResponse > srv_turtlebot_moveResponsePtr;
typedef boost::shared_ptr< ::rss2_msgsrv_pkg::srv_turtlebot_moveResponse const> srv_turtlebot_moveResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rss2_msgsrv_pkg::srv_turtlebot_moveResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rss2_msgsrv_pkg::srv_turtlebot_moveResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace rss2_msgsrv_pkg

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'nav_msgs': ['/opt/ros/kinetic/share/nav_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'rss2_msgsrv_pkg': ['/home/sam/catkin_ws/src/rss2_msgsrv_pkg/msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::rss2_msgsrv_pkg::srv_turtlebot_moveResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rss2_msgsrv_pkg::srv_turtlebot_moveResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rss2_msgsrv_pkg::srv_turtlebot_moveResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rss2_msgsrv_pkg::srv_turtlebot_moveResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rss2_msgsrv_pkg::srv_turtlebot_moveResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rss2_msgsrv_pkg::srv_turtlebot_moveResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rss2_msgsrv_pkg::srv_turtlebot_moveResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "358e233cde0c8a8bcfea4ce193f8fc15";
  }

  static const char* value(const ::rss2_msgsrv_pkg::srv_turtlebot_moveResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x358e233cde0c8a8bULL;
  static const uint64_t static_value2 = 0xcfea4ce193f8fc15ULL;
};

template<class ContainerAllocator>
struct DataType< ::rss2_msgsrv_pkg::srv_turtlebot_moveResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rss2_msgsrv_pkg/srv_turtlebot_moveResponse";
  }

  static const char* value(const ::rss2_msgsrv_pkg::srv_turtlebot_moveResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rss2_msgsrv_pkg::srv_turtlebot_moveResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool success\n\
\n\
";
  }

  static const char* value(const ::rss2_msgsrv_pkg::srv_turtlebot_moveResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rss2_msgsrv_pkg::srv_turtlebot_moveResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct srv_turtlebot_moveResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rss2_msgsrv_pkg::srv_turtlebot_moveResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rss2_msgsrv_pkg::srv_turtlebot_moveResponse_<ContainerAllocator>& v)
  {
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RSS2_MSGSRV_PKG_MESSAGE_SRV_TURTLEBOT_MOVERESPONSE_H
